# Generated by Django 4.0.4 on 2022-05-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_keep_item_id', models.CharField(db_index=True, max_length=300)),
                ('google_keep_text', models.CharField(blank=True, max_length=500)),
                ('google_keep_checked', models.BooleanField()),
                ('imdb_id', models.CharField(db_index=True, max_length=50)),
                ('imdb_title', models.CharField(max_length=300)),
                ('imdb_year', models.IntegerField()),
                ('imdb_release_date', models.DateField()),
                ('imdb_runtime_minutes', models.IntegerField()),
                ('imdb_awards', models.CharField(max_length=1000)),
                ('imdb_image', models.CharField(max_length=500)),
                ('watched', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_keep_movies_note_id', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
